### ISSUE TITLE
Add dependency file

### ISSUE THREAD

**Issue by gotschmarcel** [gorilla/mux#159]
For the people of us who use a dependency manager, instead of just simple `go get`, a dependency file would be nice ;). A simple `glide.yaml` would be awesome:

## glide.yaml
```
package: github.com/gorilla/mux
owners:
    - name: ...
      email: ...
import:
    - package: github.com/gorilla/context
      version: <commit hash or tag> # Optional
```
